apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scm
spec:
  selector:
    matchLabels:
      app: ozone
      component: scm
  serviceName: scm
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: scm
    spec:
      initContainers:
      - name: init
        image: apache/ozone
        args:
        - ozone
        - scm
        - --init
        env:
        - name: OZONE-SITE.XML_ozone.metadata.dirs
          value: /data/metadata
        volumeMounts:
        - name: data
          mountPath: /data
      containers:
      - name: main
        image: apache/ozone
        args:
        - ozone
        - scm
        env:
        - name: OZONE-SITE.XML_ozone.metadata.dirs
          value: /data/metadata
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        emptyDir: {}
